---
- name: zOS Basic
  hosts: server
  tasks:
  # ------------------------- #
  - name: Change Password History
    shell: |
            tsocmd setropts PASSWORD\(HISTORY\(12\)\)
    register: change_password_history
  - debug:
      msg: "{{ change_password_history }}"
