---
- name: zOS Basic
  hosts: server
  tasks:
  # ------------------------- #
  - name: Change Password Min
    shell: |
            tsocmd setropts password\(minchange\(1\)\)
    register: min_change
  - debug:
      msg: "{{ min_change }}"
